name: fotograf
description: Library that provides a simple gallery and camera
repository: https://github.com/kalucky0/fotograf
version: 0.2.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  camera: ^0.11.0
  flutter_staggered_grid_view: ^0.7.0
  permission_handler: ^11.3.1
  phosphor_flutter: ^2.1.0
  photo_manager_image_provider: ^2.1.1
  photo_manager: ^3.1.1
  screenshot: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter: