name: fotograf
description: Library that provides a simple gallery and camera
repository: https://github.com/kalucky0/injecta
version: 0.1.0-dev.1

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.5+5
  flutter_staggered_grid_view: ^0.7.0
  permission_handler: ^11.1.0
  phosphor_flutter: ^2.0.1
  photo_manager_image_provider: ^2.1.0
  photo_manager: ^3.0.0-dev.2
  screenshot: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter: